global:
  scrape_interval: 1s

scrape_configs:
  - job_name: "server"
    scrape_interval: 1s
    static_configs:
      - targets: ["server-dev:3000"]

  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "loki"
    scrape_interval: 1s
    static_configs:
      - targets: ["loki:3100"]

  - job_name: "grafana"
    static_configs:
      - targets: ["grafana:4000"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
